name: xrd_plotter
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - streamlit
  - numpy
  - pandas
  - matplotlib
  - scipy
  - cycler
  - kiwisolver
  - pillow
  - pyparsing
  - python-dateutil
  - pip
  - pip:
    - xrayutilities
    - scienceplots 