name: xrd_plotter
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - streamlit
  - numpy
  - pandas
  - matplotlib
  - scipy
  - pip
  - pip:
    - xrayutilities
    - scienceplots 