services:
  - type: web
    name: xrd-plotter
    env: python
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt && chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PORT
        value: 10000 